import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js + TypeScriptデモ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-4xl font-bold mb-3">メニュー</h1>
        <div className="p-10">
          <ul className='list-disc flex gap-10'>
            <li className='text-2xl font-bold hover:text-blue-500 w-48'> 
              <Link href="./todo">Todo管理</Link>
            </li>
            <li className='text-2xl font-bold hover:text-blue-500 w-48'> 
              <Link href="#">Foo</Link>
            </li>
            <li className='text-2xl font-bold hover:text-blue-500 w-48'>  
              <Link href="#">Hoge</Link>
            </li>
            <li className='text-2xl font-bold hover:text-blue-500 w-48'>  
              <Link href="#">Buzz</Link>
            </li>
          </ul>
        </div>
      </div>
    </>
  )
}
